// Looks up pre-computed R/glmnet oracle values for R-ORACLE-TAG blocks.
// Each source file's cases live in their own fixture at
// test/fixtures/<name>.oracle.json, generated by scripts/generate-oracles.mjs,
// but all fixture files are merged into one lookup keyed on hash(r, env), so
// lookup doesn't depend on which file a case came from. Merge throws if two
// files disagree on the value for the same key.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const FIXTURE_VERSION = 1;
const FIXTURES_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..", "test", "fixtures");

let fixtureCache = null;

function stableStringify(value) {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item)).join(",")}]`;
  }
  const keys = Object.keys(value).sort();
  return `{${keys.map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(",")}}`;
}

export function oracleKey(r, env) {
  const input = stableStringify({ r, env });
  return createHash("sha256").update(input).digest("hex");
}

function loadFixtureMap() {
  if (fixtureCache) return fixtureCache;

  let files;
  try {
    files = readdirSync(FIXTURES_DIR).filter((name) => name.endsWith(".oracle.json"));
  } catch (err) {
    throw new Error(`could not read fixtures directory ${FIXTURES_DIR}: ${err.message}`);
  }
  if (files.length === 0) {
    throw new Error(`no oracle fixtures found in ${FIXTURES_DIR} (run "npm run pregen:oracles")`);
  }

  const merged = {};
  for (const file of files) {
    const fixtureFile = resolve(FIXTURES_DIR, file);
    const raw = JSON.parse(readFileSync(fixtureFile, "utf8"));
    assert.equal(raw.version, FIXTURE_VERSION, `unexpected oracle version in ${fixtureFile}: ${raw.version}`);

    for (const [key, oracle] of Object.entries(raw.cases)) {
      const existing = merged[key];
      if (existing && JSON.stringify(existing.value) !== JSON.stringify(oracle.value)) {
        throw new Error(
          `oracle key collision: ${key} has conflicting values in ${existing.sourceFile} ` +
            `and ${fixtureFile}. Two (r, env) pairs hashed the same but produced different results.`,
        );
      }
      merged[key] = { ...oracle, sourceFile: fixtureFile };
    }
  }

  fixtureCache = merged;
  return fixtureCache;
}

export function evaluatedInR(r, env) {
  const key = oracleKey(r, env);
  const cases = loadFixtureMap();
  const oracle = cases[key];
  if (!oracle) {
    throw new Error(
      `missing R oracle fixture for key ${key} in ${FIXTURES_DIR} ` +
        `(run "npm run pregen:oracles" after adding/changing an R-ORACLE-TAG block)`,
    );
  }
  return oracle.value;
}
